FROM bitnami/minideb

COPY --from=ocipfs.io/layer/bafybeigovthmu5di5zxkcomwn4lt3ct2u7hatzjw6adeul7snyuvdkth4q:168-cfb9359acc6d98d593d724bb9f0fd4b12dd12688eb44ee9ac391fb3fde6c0415 / /

ENTRYPOINT [ "/foo" ]
