name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # tag=v1

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb # tag=v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up GCR
        run: gcloud auth configure-docker

      - name: Build/push
        id: docker_build
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a # tag=v2
        with:
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: gcr.io/mkm-cloud/ocipfs:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy to Cloud Run
        run: gcloud run deploy ocipfs --platform=managed --region=us-central1 --image=gcr.io/mkm-cloud/ocipfs@${{ steps.docker_build.outputs.digest }}
